In [1]:
# how to install
#pip install numpy

In [2]:
# importing numpy before using
import numpy as np

In [3]:
# creating one dimensional array from one dimension list
list1 = [1, 4, 5, 6, 1, 7]
arry1 = np.array(list1)
arry1

array([1, 4, 5, 6, 1, 7])

In [4]:
# checking the type of array
type(arry1)

numpy.ndarray

In [8]:
# creating two dimensional array from two dimensional list
list2 = [[5, 7, 0, 10, 12, 45]]
arry2 = np.array(list2)
arry2

array([[ 5,  7,  0, 10, 12, 45]])

In [9]:
# to check the dimension of array
arry2.ndim

2

In [10]:
# creating three dimensional array frome one dimension list
list2 = [5, 7, 0, 10, 12, 45]
arry3 = np.array(list2, ndmin=3, dtype="complex")
arry3

array([[[ 5.+0.j,  7.+0.j,  0.+0.j, 10.+0.j, 12.+0.j, 45.+0.j]]])

# Exercise
Create numpy of three dimensions and integer data type from the list below
[2,4,5,22,8,54,22]

In [12]:
list3 =  [2,4,5,22,8,54,22]
arry4 = np.array(list3, ndmin=3, dtype="int")
arry4

array([[[ 2,  4,  5, 22,  8, 54, 22]]])

In [13]:
# 4 NumPy - Array from Numerical Ranges
# numpy.arange(start, stop, step, dtype)
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0, 11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
# creating array using linspace
# numpy.linspace(start, stop, num, endpoint, dtype)
np.linspace(10, 50, 4, endpoint=False)

array([10., 20., 30., 40.])

# Exercise
2. Create numpy array of object data type containing just 8 element within 10 and 90.endpoint should be excluded
3. create numpy of int data type from 7 to 70 with interval of 8

In [21]:
np.linspace(10,90,8, endpoint=False, dtype=object)

array([10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0], dtype=object)

In [23]:
np.arange(7,71, 8, dtype=int)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

# Attribute of Array;

- Shape: It gives no of element in each of the dimension

In [25]:
# how to check the shape of the arr
arry5 = np.array([[[2, 5],
         [8, 3],
         [6, 4]],
        
         [[1, 6],
         [4, 0],
         [4, 5]]])

arry5.shape

(2, 3, 2)

In [26]:
arry6 = np.arange(7, 71, 8, dtype=int)
arry6.shape

(8,)

In [28]:
arry7=np.array([[2, 6, 7, 8],
               [2, 6, 7, 8],
               [2, 6, 7, 8],
               [2, 6, 7, 8],
               [2, 6, 7, 8]])
arry7.shape

(5, 4)

In [31]:
#reshaping the shape of array **`2 ReShape()`**
arry8 = np.arange(7, 71, 4, dtype=int)
print(arry8)
arry8.shape

[ 7 11 15 19 23 27 31 35 39 43 47 51 55 59 63 67]


(16,)

In [30]:
arry_reshape=arry8.reshape(4, 4)
arry_reshape.shape

(4, 4)

In [32]:
# indexing and slicing


In [43]:
num1 = [ 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67]
num1[2:14:3]

[15, 27, 39, 51]

In [37]:
# Boolean indexing

In [38]:
# to filter all element less than 30
arry8[ arry8>30]

array([31, 35, 39, 43, 47, 51, 55, 59, 63, 67])

In [41]:
# `np.flatten()` changing the dimension of array into one
arry_reshape=arry8.reshape(16, 1, 1, 1)
arry_reshape.shape

(16, 1, 1, 1)

In [42]:
arry_reshape.flatten().shape

(16,)